backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: Carousel,
              name: carousel,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: 'src/pages/coffees.md'
        label: 'Our Coffees'
        name: 'coffees'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'coffees-page',
            }
          - {
              label: Coffee Types,
              name: coffeeTypes,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: 'src/pages/ordering.md'
        label: 'Ordering'
        name: 'ordering'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'ordering-page',
            }
          - {
              label: Categories,
              name: categories,
              widget: list,
              fields:
                [
                  {
                    label: Category Title,
                    name: categoryTitle,
                    widget: string,
                  },
                  {
                    label: Subcategories,
                    name: subcategories,
                    widget: list,
                    fields:
                      [
                        {
                          label: Subcategory Title,
                          name: subcategoryTitle,
                          widget: string,
                        },
                        {
                          label: Products,
                          name: products,
                          widget: list,
                          fields:
                            [
                              { label: Name, name: name, widget: string },
                              {
                                label: Weight,
                                name: weight,
                                widget: number,
                                valueType: float,
                              },
                              {
                                label: Price,
                                name: price,
                                widget: number,
                                valueType: float,
                              },
                              {
                                label: Description,
                                name: description,
                                widget: markdown,
                                required: false,
                              },
                            ],
                        },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about.md'
        label: 'About Us'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: markdown },
                ],
            }
