backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: Carousel,
              name: carousel,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
      - file: 'src/pages/coffees.md'
        label: 'Our Coffees'
        name: 'coffees'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'coffees-page',
            }
          - {
              label: Coffee Types,
              name: coffeeTypes,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
